export const plans = [
  {
    slug: 'basic',
    name: 'Basic',
    price: '$50',
    period: '/ month',
    description: 'Entry plan for a single site and simple launch needs.',
    points: ['1 website', 'Free SSL', 'Basic storage'],
    tone: 'from-white via-[#f7faf7] to-[#edf4ee]',
  },
  {
    slug: 'pro',
    name: 'Pro',
    price: '$199',
    period: '/ month',
    description: 'For growing launches that need more capacity and protection.',
    points: ['3 websites', 'Higher performance', 'Automatic backups'],
    tone: 'from-[#f4faf5] via-[#eef7f0] to-[#e1efe4]',
    featured: true,
  },
  {
    slug: 'branding',
    name: 'Branding',
    price: '$499',
    period: '/ project',
    description: 'Identity and launch visuals for a cleaner first impression.',
    points: ['Visual identity', 'Landing page design', 'Product presentation'],
    tone: 'from-[#fcfaf6] via-[#f9f4e9] to-[#f4ebd9]',
  },
  {
    slug: 'business',
    name: 'Business',
    price: '$1000+',
    period: '/ month',
    description: 'Custom setup for larger builds and higher-touch support.',
    points: ['Unlimited websites', 'Priority support', 'Advanced security'],
    tone: 'from-white via-[#f7faf7] to-[#edf4ee]',
  },
];
